import { writeFileSync } from "node:fs";
import { join } from "node:path";

type DeployContext = "production" | "pr-preview" | "branch-preview";

interface WranglerRoute {
  pattern: string;
  custom_domain?: boolean;
  zone_name?: string;
}

interface WranglerConfig {
  name: string;
  compatibility_date: string;
  account_id: string;
  assets: { directory: string };
  routes: WranglerRoute[];
}

function sanitizeBranchName(branch: string): string {
  return branch
    .toLowerCase()
    .replace(/[/.]/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 28);
}

function buildConfig(context: DeployContext): WranglerConfig {
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
  if (!accountId) {
    throw new Error("CLOUDFLARE_ACCOUNT_ID environment variable is required");
  }

  const base: Omit<WranglerConfig, "name" | "routes"> = {
    compatibility_date: "2026-02-14",
    account_id: accountId,
    assets: { directory: "./site/.vitepress/dist" },
  };

  switch (context) {
    case "production":
      return {
        ...base,
        name: "bind-directory",
        routes: [
          { pattern: "bindpki.org", custom_domain: true },
          { pattern: "www.bindpki.org", custom_domain: true },
        ],
      };

    case "pr-preview": {
      const prNumber = process.env.PR_NUMBER;
      if (!prNumber) {
        throw new Error("PR_NUMBER environment variable is required for pr-preview context");
      }
      return {
        ...base,
        name: `bind-directory-pr-${prNumber}`,
        routes: [
          {
            pattern: `${prNumber}-pr-preview.bindpki.org`,
            zone_name: "bindpki.org",
          },
        ],
      };
    }

    case "branch-preview": {
      const branchName = process.env.BRANCH_NAME;
      if (!branchName) {
        throw new Error("BRANCH_NAME environment variable is required for branch-preview context");
      }
      const sanitized = sanitizeBranchName(branchName);
      return {
        ...base,
        name: `bind-directory-${sanitized}`,
        routes: [
          {
            pattern: `${sanitized}-preview.bindpki.org`,
            zone_name: "bindpki.org",
          },
        ],
      };
    }

    default:
      throw new Error(`Unknown DEPLOY_CONTEXT: ${context}`);
  }
}

const context = (process.env.DEPLOY_CONTEXT || "production") as DeployContext;
const config = buildConfig(context);
const outputPath = join(__dirname, "..", "wrangler.jsonc");

const content = `// Auto-generated by scripts/generate-wrangler-config.ts — do not edit manually
${JSON.stringify(config, null, 2)}
`;

writeFileSync(outputPath, content);
console.log(`Generated wrangler.jsonc (context: ${context}, name: ${config.name})`);
